BTA/Models/POI.cs
namespace BTA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;

    [Table("POI")]
    public partial class POI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POI()
        {
            Lines = new HashSet<Line>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long PoiId { get; set; }

        public long? CityId { get; set; }

        [StringLength(50)]
        public string Name { get; set; }

        [StringLength(150)]
        public string Address { get; set; }

        [StringLength(2083)]
        public string Website { get; set; }

        [StringLength(2083)]
        public string PoiImg { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        public double Rating { get; set; }

        public double? Lon { get; set; }

        public double? Lat { get; set; }

        [StringLength(50)]
        public string Phone { get; set; }

        [StringLength(50)]
        public string Email { get; set; }

        public long? CategoryId { get; set; }

        public string POIDescription { get; set; }

        public bool Active { get; set; }

        public bool? Transport { get; set; }

        public virtual Category Category { get; set; }

        public virtual City City { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Line> Lines { get; set; }
    }
}

BTA/Controllers/POIsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTA.Models;
using System.Configuration;
using System.IO;

namespace BTA.Controllers
{
    public class POIsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: POIs
        public async Task<ActionResult> Index()
        {
            var pOIs = db.POIs.Include(p => p.Category).Include(p => p.City);
            return View(await pOIs.ToListAsync());
        }

        public async Task<ActionResult> PoiLoader(long catid, long cityid)
        {
            var city = db.Cities.Where(c => c.CityId == cityid).Select(c => c.CityName).FirstOrDefault();
            var category = db.Categories.Where(c => c.CategoryId == catid).Select(c => c.CategoryName).FirstOrDefault();
            ViewBag.City = city;
            ViewBag.Category = category;
            var pOIs = db.POIs.Include(p => p.Category).Include(p => p.City).Where(p => p.Category.CategoryId == catid).Where(p => p.City.CityId == cityid);
            return View(await pOIs.ToListAsync());
        }

        public ActionResult RecentPOIs(long id)
        {
            var recentPOIs = db.Categories.Where(c => c.Module == id).Join(db.POIs, c => c.CategoryId, p => p.CategoryId, (c, p) => p)
                                          .ToList().OrderByDescending(p => p.PoiId).Take(4);

            return PartialView(recentPOIs);
        }

        public ActionResult RecentPoisByCategory(long catId, long cityId)
        {
            var pois = db.POIs.Where(p => p.CategoryId == catId && p.CityId == cityId).Select(p => p).ToList().Take(3);

            return PartialView(pois);
        }

        // GET: POIs/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            POI pOI = await db.POIs.FindAsync(id);
            if (pOI == null)
            {
                return HttpNotFound();
            }
            return View(pOI);
        }

        // GET: POIs/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
            ViewBag.CityId = new SelectList(db.Cities, "CityId", "CityName");
            return View();
        }

        // POST: POIs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PoiId,CityId,Name,Address,Website,PoiImg,Rating,Lon,Lat,Phone,Email,CategoryId,POIDescription,Active")] POI pOI, string catMark, HttpPostedFileBase imageFile, string website)
        {
            catMark = Convert.ToString(catMark);

            if (catMark == "classicPoi")
            {
                var web = pOI.Website;
                var city = db.Cities.Where(c => c.CityId == pOI.CityId).Select(c => c.CityName).FirstOrDefault();
                var cleanURl = "";
                var category = db.Categories.Where(c => c.CategoryId == pOI.CategoryId).Select(c => c.CategoryName).FirstOrDefault();
                var moduleId = db.Categories.Where(c => c.CategoryId == pOI.CategoryId).Select(c => c.Module).FirstOrDefault();
                var module = db.Modules.Where(m => m.ModuleId == moduleId).Select(m => m.ModuleName).FirstOrDefault();

                if (category == "Food & Entertainment" || module == "Accomodation")
                {
                    if (web.Contains("aid="))
                    {
                        var firstIndex = web.IndexOf("aid=");
                        var lastIndex = web.IndexOf("aid=") + 11;
                        var substring = web.Substring(firstIndex, lastIndex);
                        cleanURl = web.Replace(substring, "");
                    }
                    else
                    {
                        cleanURl = web;
                    }

                    var url = Uri.EscapeDataString(cleanURl);
                    var ogKey = Environment.ExpandEnvironmentVariables(
                            ConfigurationManager.AppSettings["OpenGraphAPI"]);
                    var requestUrl = "https://opengraph.io/api/1.1/site/" + url + "?app_id=" + ogKey;
                    dynamic ogResults = new Uri(requestUrl).GetDynamicJsonObject();

                    pOI.Name = Convert.ToString(ogResults.hybridGraph.title);
                    if (cleanURl.Contains("booking")) { pOI.Name = pOI.Name.Split(',')[0]; }
                    else if (cleanURl.Contains("airbnb")) { pOI.Name = pOI.Name.Split('-')[0] + ", " + pOI.Name.Split('-')[1] + ", " + city; }

                    pOI.POIDescription = Convert.ToString(ogResults.hybridGraph.description);
                    pOI.PoiImg = Convert.ToString(ogResults.hybridGraph.image);

                    string gcUrl = "https://maps.googleapis.com/maps/api/geocode/json?sensor=true&address=";
                    string gcKey = Environment.ExpandEnvironmentVariables(
                            ConfigurationManager.AppSettings["GoogleAPI"]);

                    string key = "&key=" + gcKey;

                    dynamic googleResults = new Uri(gcUrl + pOI.Name + key).GetDynamicJsonObject();
                    pOI.Lon = Convert.ToDouble(googleResults.results[0].geometry.location.lng);
                    pOI.Lat = Convert.ToDouble(googleResults.results[0].geometry.location.lat);
                    pOI.Address = Convert.ToString(googleResults.results[0].formatted_address);
                } // This is where opengraph code ends

                pOI.Active = true;

                if (ModelState.IsValid)
                {
                    db.POIs.Add(pOI);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }

            if (catMark == "transportPoi")
            {   
                pOI.Rating = 0;
                pOI.Active = true;
                pOI.Address = null;
                pOI.Website = website;
               
                if (imageFile != null)
                {
                    string extension = Path.GetExtension(imageFile.FileName);
                    string photoName = Convert.ToString("trans_" + pOI.Name.Replace(" ", "_"));
                    string fileName = photoName + extension;
                    pOI.PoiImg = "/Assets/Images/POIs/" + fileName;
                    fileName = Path.Combine(Server.MapPath("/Assets/Images/POIs/"), fileName);
                    pOI.ImageFile = imageFile;
                    pOI.ImageFile.SaveAs(fileName);
                }
                else
                {
                    pOI.ImageFile = null;
                }

                if (ModelState.IsValid)
                {
                    db.POIs.Add(pOI);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", pOI.Category);
            ViewBag.CityId = new SelectList(db.Cities, "CityId", "CityName", pOI.City);
            return View(pOI);
        }

        // GET: POIs/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            POI pOI = await db.POIs.FindAsync(id);
            if (pOI == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", pOI.CategoryId);
            ViewBag.CityId = new SelectList(db.Cities, "CityId", "CityName", pOI.CityId);
            return View(pOI);
        }

        // POST: POIs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PoiId,CityId,Name,Address,Website,PoiImg,Rating,Lon,Lat,Phone,Email,CategoryId,POIDescription,Active")] POI pOI)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pOI).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", pOI.CategoryId);
            ViewBag.CityId = new SelectList(db.Cities, "CityId", "CityName", pOI.CityId);
            return View(pOI);
        }

        // GET: POIs/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            POI pOI = await db.POIs.FindAsync(id);
            if (pOI == null)
            {
                return HttpNotFound();
            }
            return View(pOI);
        }

        // POST: POIs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            POI pOI = await db.POIs.FindAsync(id);
            db.POIs.Remove(pOI);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {

BTA/Views/POIs/Create.cshtml
@model BTA.Models.POI

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "POIs", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>POI</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @*@Html.LabelFor(model => model.City, "city", htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.DropDownList("CityId", null, "Choose city", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.Category, "category", htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", null, "Choose category", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
        </div>
    </div>

    <input id="categoryMark" type="hidden" name="catMark" value="" />
    <input id="weburl" type="hidden" name="website" value="" />
    @*////////////////////CLASSIC POI////////////////////////////////////////*@

    <div class="classicPoi">
        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control", validateRequest = "false" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    @*////////////////////TRANSPORT////////////////////////////////////////*@

    <div class="transportPoi d-none">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PoiImg, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <input type="file" name="imageFile" />
                @*@Html.ValidationMessageFor(model => model.ImgUrl, "", new { @class = "text-danger" })*@
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Lon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Lon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Lon, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Lat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Lat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Lat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.POIDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.POIDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.POIDescription, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Transport, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Transport)
                @Html.ValidationMessageFor(model => model.Transport, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="sbmtBtn" type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/poiCreate.js"></script>

BTA/Views/POIs/Delete.cshtml
@model BTA.Models.POI

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>POI</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PoiImg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PoiImg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.POIDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.POIDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BTA/Views/POIs/Details.cshtml
@model BTA.Models.POI

@{
    ViewBag.Title = "Details";
<link href="~/Content/Site.css" rel="stylesheet" />
}

<h2>Details for @Html.DisplayFor(model => model.Category.CategoryName)</h2>

<div>
    <h4>@Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <dl class="dl-horizontal">


        <input id="PoiId" type="hidden" name="PoiId" value="@Model.PoiId" />
        <input id="TableName" type="hidden" name="name" value="@Model.GetType().Name.Split('_')[0]" />


        <dd>
            <img class="d-inline-block" src="@Html.DisplayFor(model => model.PoiImg)" /> <p class="d-inline-block">@Html.DisplayFor(model => model.POIDescription)</p>
            <p>Address: @Html.DisplayFor(model => model.Address)</p>
            <p><a href="@Html.DisplayFor(model => model.Website)">Website</a></p>
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>*@


    </dl>
</div>

@Html.HiddenFor(model => model.PoiId)
@*@Html.ActionLink("Add feedback", "Create", "Comments", new { id = Model.PoiId })*@
<div class="add-comment" style="display: none;"></div>
<p>
    <span class="add-comment-button ">Add feedback</span>
</p>
<div class="comment-section"></div>

@*@Html.Partial("Index",)*@
@*@RenderPage("~/Views/Comments/Index/" + Model.PoiId )*@
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PoiId }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.PoiId })

    @Html.ActionLink("Back to List", "Index")
</p>
<script src="~/Scripts/CommentLoader.js"></script>

BTA/Views/POIs/Edit.cshtml
@model BTA.Models.POI

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>POI</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PoiId)

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, "CityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PoiImg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PoiImg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PoiImg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.POIDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.POIDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.POIDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}