BTA/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTA.Models;
using BTA.ViewModels;

namespace BTA.Controllers
{
    public class ModulesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Modules
        public async Task<ActionResult> Index()
        {
            return PartialView(await db.Modules.ToListAsync());
        }

        // GET: Modules/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = await db.Modules.FindAsync(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            var citiesAll = db.Cities.Select(c => c.Country).Distinct().ToList();
            ViewBag.Country = new SelectList(citiesAll);
            //ViewBag.Country = new SelectList(from c in citiesAll select new { c.Country , countryName = c.Country }, "Country", "countryName");
            var categories = db.Modules.Where(m => m.Active == true && m.ModuleId == id).Select(m => m.Categories).ToList();

            return View(module);
        }

        // GET: Modules/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Modules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ModuleId,ModuleName,Active")] Module module)
        {
            if (ModelState.IsValid)
            {
                db.Modules.Add(module);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(module);
        }

        // GET: Modules/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = await db.Modules.FindAsync(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        // POST: Modules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ModuleId,ModuleName,Active")] Module module)
        {
            if (ModelState.IsValid)
            {
                db.Entry(module).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(module);
        }

        // GET: Modules/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = await db.Modules.FindAsync(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        // POST: Modules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            Module module = await db.Modules.FindAsync(id);
            db.Modules.Remove(module);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        ///CUSTOM METHODS///
        public JsonResult PopulateCities(string value)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var citiesByCountry = db.Cities.Where(c => c.Country == value).Select(c => c).ToList();

            return new JsonResult { Data = citiesByCountry, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult NavBar()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var test = db.Modules.Where(m => m.Active == true).ToListAsync();
            return new JsonResult { Data = test, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}

BTA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BTA by ČĎŠ</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/CustomStyle.css" rel="stylesheet" />
</head>
<body>
    <div class="all-wrapper">

        @{Html.RenderPartial("~/Views/Modules/NavBar.cshtml");}
        
        <div class="container body-content">
            @RenderBody()
            @*@Html.Partial("_map")*@
            @*<div id="map_wrap">
                    <div id="map" class="map w-100" style="height: 300px;">
                    </div>
                </div>*@
            @*<hr />*@
            <footer class="d-none my-5">
                <p>&copy; @DateTime.Now.Year - BTA by ČĎŠ</p>
            </footer>
        </div>
    </div>

    <script>
        window.addEventListener("load", function () {
            setTimeout(function () {
                document.querySelector("footer").classList.remove("d-none");
            },1200)
        })

        if (document.querySelector(".add-comment-button")) {
            var commentButton = document.querySelector(".add-comment-button");
            commentButton.addEventListener("click", function () {
                if (commentButton.innerHTML == "Add feedback") {
                    commentButton.innerHTML = "Close";
                }
                else {
                    commentButton.innerHTML = "Add feedback";
                }
            })
            
        }
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript" charset="utf-8"
            src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
    <script type="text/javascript" charset="utf-8"
            src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js"></script>
    <script type="text/javascript" charset="utf-8"
            src="http://maps.google.com/maps/api/js?key=AIzaSyA-qm5hKM1LNP1RV5Y1hfPVMUlj92UUUIg&sensor=false"></script>
    <script src="~/Scripts/NavBar.js"></script>
    <script src="~/Scripts/mapLoader.js"></script>


</body>
</html>

BTA/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title- BTA by ČĎŠ</title><link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/CustomStyle.css" rel="stylesheet" />
</head>
<body>
    <div class="all-wrapper">

        @{Html.RenderPartial("~/Views/Modules/NavBar.cshtml");}
        
        <div class="container body-content">
            @RenderBody()
            
            <footer class="d-none my-5">
                <p>&copy; @DateTime.Now.Year - BTA by ČĎŠ</p>
            </footer>
        </div>
    </div>

    <script>
        window.addEventListener("load", function () {
            setTimeout(function () {
                document.querySelector("footer").classList.remove("d-none");
            },1200)
        })

        if (document.querySelector(".add-comment-button")) {
            var commentButton = document.querySelector(".add-comment-button");
            commentButton.addEventListener("click", function () {
                if (commentButton.innerHTML == "Add feedback") {
                    commentButton.innerHTML = "Close";
                }
                else {
                    commentButton.innerHTML = "Add feedback";
                }
            })
            
        }
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript" charset="utf-8"
            *src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
    <script type="text/javascript" charset="utf-8"
            src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js"></script>
    <script type="text/javascript" charset="utf-8"
            src="http://maps.google.com/maps/api/js?key=AIzaSyA-qm5hKM1LNP1RV5Y1hfPVMUlj92UUUIg&sensor=false"></script>
    <script src="~/Scripts/NavBar.js"></script>
    <script src="~/Scripts/mapLoader.js"></script>


</body>
</html>

BTA/Views/Shared/_map.cshtml
@*<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link href="/Content/Site.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" charset="utf-8"
            src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
    <script type="text/javascript" charset="utf-8"
            src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js"></script>
    <script type="text/javascript" charset="utf-8"
            src="http://maps.google.com/maps/api/js?key=AIzaSyA-qm5hKM1LNP1RV5Y1hfPVMUlj92UUUIg&sensor=false"></script>
    <script type="text/javascript">
        var center = new google.maps.LatLng(-34.397, 150.644);
        $(document).ready(function () {
            map = new google.maps.Map(document.querySelector(".map"), {
                zoom: 6,
                center: center,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });
        });
    </script>
</head>
<body>
    <div id="map_wrap">
        <div id="map" class="map w-100" style="height: 300px;">
        </div>
    </div>
</body>
</html>*@

BTA/Views/Shared/nav.cshtml
@model IEnumerable<BTA.Models.Module>
    
@foreach (var it in Model)
{
    @Html.ActionLink(it.ModuleName, "Details", "Modules", new { id = it.ModuleId })
}
    