BTA/Models/City.cs
namespace BTA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    [Table("City")]
    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            Lines = new HashSet<Line>();
            Lines1 = new HashSet<Line>();
            POIs = new HashSet<POI>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long CityId { get; set; }

        [Required]
        [StringLength(20)]
        public string CityName { get; set; }

        [StringLength(20)]
        public string Country { get; set; }

        public double? Lon { get; set; }

        public double? Lat { get; set; }

        public int? Population { get; set; }

        [StringLength(2083)]
        public string ImgUrl { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        public bool Active { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Line> Lines { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Line> Lines1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POI> POIs { get; set; }
    }
}

BTA/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTA.Models;
using System.Configuration;
using System.IO;

namespace BTA.Controllers
{
    public class CitiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cities
        public async Task<ActionResult> Index()
        {
            return View(await db.Cities.ToListAsync());
        }

        // GET: Cities/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = await db.Cities.FindAsync(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(City city)
        {
           var cityName = city.CityName;

            System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Ssl3
                    | System.Net.SecurityProtocolType.Tls
                    | System.Net.SecurityProtocolType.Tls11
                    | System.Net.SecurityProtocolType.Tls12;

            //google geocoding api
            string gcUrl = "https://maps.googleapis.com/maps/api/geocode/json?sensor=true&address=";
            string apiKey = Environment.ExpandEnvironmentVariables(
                    ConfigurationManager.AppSettings["GoogleAPI"]);

            string key = "&key=" + apiKey;

            dynamic googleResults = new Uri(gcUrl + cityName + key).GetDynamicJsonObject();

            //opendatasoft api - population 
            string odUrl = "https://public.opendatasoft.com/api/records/1.0/search/?dataset=worldcitiespop&sort=population&facet=city&refine.city=" + cityName.ToLower();
            dynamic populationResults = new Uri(odUrl).GetDynamicJsonObject();

            city.CityName = Convert.ToString(googleResults.results[0].address_components[0].long_name);
            city.Country = Convert.ToString(googleResults.results[0].address_components[googleResults.results[0].address_components.Length - 1].long_name);
            city.Lat = Convert.ToDouble(googleResults.results[0].geometry.location.lat);
            city.Lon = Convert.ToDouble(googleResults.results[0].geometry.location.lng);
            city.Population = Convert.ToInt32(populationResults.records[0].fields.population);
            city.Active = true;

            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(city);
        }

        // GET: Cities/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = await db.Cities.FindAsync(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CityId,CityName,Country,Lon,Lat,Population,ImgUrl,Active")] City city, HttpPostedFileBase imageFile)
        {
            if (imageFile != null)
            {
                string extension = Path.GetExtension(imageFile.FileName);
                string photoName = city.CityName;
                string fileName = photoName + extension;
                city.ImgUrl = "~/Assets/Images/Cities/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Assets/Images/Cities/"), fileName);
                city.ImageFile = imageFile;
                city.ImageFile.SaveAs(fileName);
            }
            else
            {
                city.ImageFile = null;
            }

            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = await db.Cities.FindAsync(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            City city = await db.Cities.FindAsync(id);
            db.Cities.Remove(city);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public static SelectList GetCountries()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            return new SelectList(db.Cities.Select(c => c.Country.Distinct()));
        }
    }
}

BTA/Views/Cities/Create.cshtml
@model BTA.Models.City

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Cities", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.cityId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.cityId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.cityId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.country, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.country, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.country, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.lon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.lon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.lon, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.lat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.lat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.lat, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.ImgUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImgUrl, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImgUrl, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.ImgUrl, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <input type="file" name="imageFile" />
                @*@Html.ValidationMessageFor(model => model.ImgUrl, "", new { @class = "text-danger" })*@
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.population, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.population, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.population, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BTA/Views/Cities/Delete.cshtml
@model BTA.Models.City

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Population)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Population)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImgUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BTA/Views/Cities/Details.cshtml
@model BTA.Models.City

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">

        <input id="CityId" type="hidden" name="CityId" value="@Model.CityId" />
        <input id="TableName" type="hidden" name="name" value="@Model.GetType().Name.Split('_')[0]" />

        @*<dt>
                @Html.DisplayNameFor(model => model.CityName)
            </dt>*@

        <dd>
            @Html.DisplayFor(model => model.CityName), @Html.DisplayFor(model => model.Country)
        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.Country)
            </dt>*@

        @*<dd>

            </dd>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.Lon)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Lon)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Lat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Lat)
            </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Population)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Population)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImgUrl)
        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.Active)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Active)
            </dd>*@

    </dl>
    <p>
        <div class="add-comment-button">Add feedback</div>
    </p>
    @Html.HiddenFor(model => model.CityId)
    <div class="add-comment" style="display: none;"></div>
    <div class="comment-section"></div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CityId }) |
    @Html.ActionLink("Back to List", "Index")
</p>
@*<script src="~/Scripts/CommentLoader.js"></script>*@
<script src="~/Scripts/CommentLoader.js"></script>

BTA/Views/Cities/Edit.cshtml
@model BTA.Models.City

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Cities", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CityId)

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Population, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Population, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Population, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="pl-3">Edit if image exists:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImgUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImgUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="pl-3">Choose picture:</label>
            <div class="col-md-10">
                <input type="file" name="imageFile" />
                @*@Html.ValidationMessageFor(model => model.ImgUrl, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BTA/Views/Cities/Index.cshtml
@model IEnumerable<BTA.Models.City>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CityName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Population)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImgUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CityName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Population)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImgUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CityId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CityId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CityId })
        </td>
    </tr>
}

</table>